#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''
Created on 2014-3-19

@author: Wenjun Hu
'''
# package_name : ('ad_name', 'ad_url')

AD_MODULE_MAP = {  
      'Lcom/google/ads':('AdMob','http://www.google.com/ads/admob/'),
      'Lcom/admob/andorid/ads': ('AdMob', 'http://www.google.com/ads/admob/'),
      'Lcom/millennialmedia/android':('MillennialMedia','http://www.millennialmedia.com/'),
      'Lcom/inmobi/androidsdk':('InMobi','http://www.inmobi.com/'),
      'Lcom/chartboost/sdk': ('Chartboost', 'https://www.chartboost.com/'),
      'Lcom/tapjoy': ('Tapjoy', 'http://home.tapjoy.com/'),
      'Lcom/mopub/mobileads': ('Mopub', 'http://www.mopub.com/'),
      'Lcom/jirbo/adcolony': ('AdColony', 'http://www.adcolony.com/'),
      'Lcom/sponsorpay/advertiser': ('Sponsorpay', 'http://www.sponsorpay.com/'),
      'Lcom/appbrain': ('AppBrain', 'http://www.appbrain.com/'),
      'Lcom/adsdk/sdk': ('Adserver', 'http://www.madserve.org/'),
      'Lcom/getjar/sdk': ('GetJar', 'https://www.getjar.com/android'),
      'Lcom/adwhirl': ('AdWhirl', 'http://code.google.com/p/adwhirl/'),
      'Lcom/heyzap/sdk/ads': ('HeyZap', 'http://www.heyzap.com/'),
      'Lcom/waps': ('Waps', 'http://www.waps.cn/'),
      'Lcom/adchina': ('AdChina','http://www.adchina.com/'),
      'Lcom/tapit/adview': ('Tapit', 'http://www.tapit.com/'),
      'Lcom/Leadbolt': ('LeadBolt', 'http://www.leadbolt.com/'),
      'Lcom/appenda': ('Appenda', 'http://www.appenda.com/'),
      'Lcom/airpush/android': ('AirPush', 'http://www.airpush.com/'),
      'Lcom/moolah': ('Moolah Media', 'http://www.moolahmedia.com/'),
      'Lnet/youmi/android': ('Youmi', 'http://www.youmi.net/'),
      'Lcn/domob/android/ads': ('Domob', 'http://www.domob.cn/'),
      'Lcom/wooboo/adlib_android':('Wooboo','http://www.wooboo.com.cn/'),
      'Lcom/adwo/adsdk':('AdWo','http://www.adwo.com/'),
      'Lcom/sosceo/android/ads': ('Sosceo', 'http://www.sosceo.com/'),
      'Lcom/winad/android/banner/ads': ('Winads', 'http://www.winads.cn/'),
      'Lcom/mt/airad': ('AirAD', 'http://www.airad.com/'),
      'Lcom/wqmobile/sdk': ('Wqmobile', 'http://www.wqmobile.com/'),
      'Lcom/tencent/mobwin':('MobWin','http://dev.app.qq.com/indexInit.action'),
      'Lcom/mobus/ad': ('Mobus', 'http://www.mobus.cn'),
      'Lcom/ju6/AdRequester':('Ju6', ''),
      'Lcom/apperhand/device/android': ('ApperHand', ''),
      'Lcn/casee': ('Casee', 'http://www.casee.cn/mm/Index.ad'),
      'Lcom/LogiaGroup/AdCore': ('LogiaAD', ''),
      'Lcom/greystripe/android/sdk': ('GreyStripe', 'http://www.greystripe.com/'),
      'Lcom/everbadge/connect': ('Everbadge', 'http://everbadge.com/'),
      'Lbuzzcity/android/sdk': ('BuzzCity', 'http://www.buzzcity.com/'),
      'Lcom/admia/android': ('AdMia', ''),
      'Lcom/adknowledge/superrewards': ('AdKnowledge', 'http://www.adknowledge.com/'),
      'Lcom/jumptap/adtag': ('JumpTap', 'http://www.millennialmedia.com/'),
      'Lcom/mdotm/android/ads': ('MDotM', 'http://www.mdotm.com/'),
      'Lcom/medialets/advertising': ('Medialets', 'http://www.medialets.com/'),
      'Lcom/mobfox/sdk': ('MobFox', 'http://www.mobfox.com/'),
      'Lcom/adserver/adview': ('MOcean', 'http://www.moceanmobile.com/'),
      'Lcom/pontiflex/mobile': ('Pontiflex', 'http://www.pontiflex.com/'),
      'Lcom/smaato/SOMA': ('Smaato', 'http://www.smaato.com/'),
      'Lcom/vdopia/client/android': ('Vdopia', 'http://www.vdopia.com/mobile/'),
      'Lmmobi/vserv/android/adengine': ('Vserv', 'http://www.vserv.mobi/'),
      'Lcom/wiyun/ad/AdView': ('Wiyun', 'http://www.weiyun.com/index.html'),
      'Lcom/vpon/adon/android/AdView':('VPON', 'http://www.vpon.com/'),
      'Lcom/mobclix/android/sdk': ('Mobclick', ''),
      'Lcn/appmedia/ad/AdManager': ('Appmedia', 'http://www.appmedia.cn'),
      'Lnet/miidi/ad': ('Miidi', 'http://www.miidi.net/'),
      'Lcom/aiwan/AdView': ('iAiwan', 'http://www.iaiwan.com/'),
      'Lcom/juzi/main/AdView': ('Juzi', 'http://www.juzi.cn/'),
      'Lcom/adpush/pushAPush': ('AdPush', 'http://www.adpush.cn/'),
      'Lcom/fengchi': ('Fengchi', ''),
      'Lcom/kuguo/pushads': ('KuGuo', 'http://www.kuguopush.com/'),
      'Lcom/adfonic/android': ('AdFonic', 'http://adfonic.com/'),
      'Lcom/aduru/sdk': ('Aduru', ''),
      'Lcom/burstly/lib': ('Burstly', 'http://www.burstly.com/'),
      'Lcom/cauly/android/ad': ('Cauly','http://www.cauly.net/index.php/w/home'),
      'Lcom/sellaring/sdk': ('SellARing', 'http://www.sellaring.com/'),
      'Lcom/zestadz/android': ('ZestAdz', 'http://www.komlimobile.com/'),
      'Lme/gall/mercury': ('Mercury', 'http://gall.me/'),
      'Lcom/w/sta':('G3app',''),
      'Lcom/urbanairship/push': ('Urban Airship', 'http://urbanairship.com/'),
      'Lcom/ignitevision/andoroid': ('Tinmoo', 'http://www.tinmoo.com/mobile/index.do'),
      'Lcom/l/adlib_android': ('LSense','http://www.lsense.cn/'),
      'Lcom/izp': ('Izp','http://www.izptec.com/cn/'),
      'Lcom/mobisage': ('Mobisage', 'http://mobisage.ad-sage.com/'),
      'Lcom/umengAd': ('Umeng', 'http://ads.umeng.com/'),
      'Lcom/fractalist': ('Fractalist', 'http://www.admarket.mobi/'),
      'Lcom/immob/sdk': ('Limei','http://www.limei.com/'),
      'Lcn/aduu/adsdk': ('Aduu','http://www.aduu.cn/'),
      'Lcom/emar/escore': ('Yijifen', 'http://www.yijifen.com'),
      'Lcom/kyview': ('Adview','http://www.adview.cn'),
      'Lcom/energysource': ('Adtouch','http://www.adtouchnetwork.com/'),
      'Lcom/guohead/sdk': ('GuoHead','http://www.guohead.com'),
      'Lcom/baidu/mobads': ('Baidu','http://munion.baidu.com/'),
      'Lcom/fortumo': ('Fortumo', 'http://fortumo.com/'),
      'Lcom/flurry': ('Flurry', 'http://www.flurry.com/'),
      'Lcom/skyhookwireless': ('Skyhookwireless', 'http://www.skyhookwireless.com/'),
      'Lcom/dianru/sdk': ('DianRu', 'http://www.dianru.com/'),
      'Lcom/fractalist/android/ads': ('Fractalist', 'http://www.fractalist.com.cn/'),
      'Lcom/energysource/szj': ('Energy Source', 'http://www.energysource-cn.com/'),
      'Lcom/dianjoy': ('DianJoy', 'http://www.dianjoy.com/'),
      'Lcom/adzhidian/manager/service/AdService': ('ZhiDian', 'http://www.zhidian3g.com/'),
      'Lcom/qq/e/ads': ('GuangDianTong', 'http://e.qq.com/'),  
      'Lcom/adsmogo': ('AdsMogo', 'http://www.adsmogo.com/'),
      'Lcom/papaya/offer': ('Papaya', 'http://papayamobile.com/'),
    };
